-- PERF: installing formatters and linters for python,lua and c++
--
-- local none_ls = require("null-ls")
--
-- none_ls.setup({
-- 	sources = {
-- 		none_ls.builtins.formatting.stylua,
-- 		none_ls.builtins.formatting.clang_format,
-- 	},
-- })
